import type { DemoState } from "./types";

export const DEMO_STORAGE_KEY = "lumina-demo-store-v1";

export function createSeedState(): DemoState {
  return {
    members: [
      { id: "1", name: "Sarah Jenkins", email: "sarah.j@example.com", phone: "+1 (555) 123-4567", role: "Elder", status: "Active", stage: "Leadership", joined: "Mar 2019", groups: ["g1"], lastActivity: "2 days ago", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80" },
      { id: "2", name: "Michael Roberts", email: "m.roberts@example.com", phone: "+1 (555) 987-6543", role: "Member", status: "Active", stage: "Regular", joined: "Jun 2021", groups: ["g2"], lastActivity: "Today", initials: "MR" },
      { id: "3", name: "David Chen", email: "d.chen@example.com", phone: "+1 (555) 234-5678", role: "Deacon", status: "Inactive", stage: "Leadership", joined: "Jan 2018", groups: [], lastActivity: "4 months ago", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80" },
      { id: "4", name: "Emily Wong", email: "emily.w@example.com", phone: "+1 (555) 345-6789", role: "Volunteer", status: "Active", stage: "Regular", joined: "Sep 2022", groups: ["g1", "g3"], lastActivity: "Yesterday", initials: "EW" },
      { id: "5", name: "Paul & Anna Schmidt", email: "schmidt.family@example.com", phone: "+1 (555) 456-7890", role: "Member", status: "Pending", stage: "New", joined: "May 2026", groups: [], lastActivity: "—", initials: "PS", needsReview: true },
      { id: "6", name: "Nadia Kouassi", email: "n.kouassi@example.com", phone: "+1 (555) 567-8901", role: "Member", status: "Pending", stage: "New", joined: "May 2026", groups: [], lastActivity: "—", initials: "NK", needsReview: true },
      { id: "7", name: "James Moreau", email: "j.moreau@example.com", phone: "+1 (555) 678-9012", role: "Elder", status: "Active", stage: "Leadership", joined: "Nov 2015", groups: ["g2"], lastActivity: "3 days ago", initials: "JM" },
      { id: "8", name: "Sophie Chen", email: "s.chen@example.com", phone: "+1 (555) 789-0123", role: "Volunteer", status: "Active", stage: "Regular", joined: "Feb 2020", groups: ["g1"], lastActivity: "1 week ago", initials: "SC" },
      { id: "9", name: "Marie Dubois", email: "marie.d@email.com", phone: "+1 555 0101", role: "Member", status: "Active", stage: "Regular", joined: "Aug 2017", groups: ["g2"], lastActivity: "Today", initials: "MD" },
      { id: "10", name: "Lucas Martin", email: "l.martin@email.com", phone: "+1 555 0108", role: "Member", status: "Active", stage: "Regular", joined: "Apr 2020", groups: ["g3"], lastActivity: "2 days ago", initials: "LM" },
    ],
    groups: [
      { id: "g1", slug: "young-professionals", name: "Downtown Young Professionals", category: "Young Adults", categoryClass: "bg-[#e5deff] text-[#4404d7]", desc: "A gathering for young professionals navigating faith, career, and relationships.", schedule: "Wednesdays", time: "7:00 PM", location: "Central Cafe", members: 24, memberIds: ["1", "4", "8"], image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80", featured: true, active: true },
      { id: "g2", slug: "mens-study", name: "Morning Men's Study", category: "Bible Study", categoryClass: "bg-[#b3ebff] text-[#001f27]", desc: "Early morning fellowship focusing on practical application of scripture.", schedule: "Thursdays", time: "6:00 AM", location: "Main Campus, Room 102", members: 15, memberIds: ["2", "7", "9"], image: "https://images.unsplash.com/photo-1504052434569-70ad58346a20?w=600&q=80" },
      { id: "g3", slug: "food-bank", name: "Community Food Bank", category: "Outreach", categoryClass: "bg-[#ffdbcd] text-[#360f00]", desc: "Weekly volunteer group organizing and distributing food to local families.", schedule: "Saturdays", time: "9:00 AM", location: "Eastside Community Center", members: 42, memberIds: ["4", "10"], image: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&q=80" },
      { id: "g4", slug: "parents-teens", name: "Parents of Teens", category: "Support", categoryClass: "bg-[#e0e3e5] text-[#191c1e]", desc: "A supportive environment for parents to share experiences and encouragement.", schedule: "Bi-weekly Tuesdays", time: "7:00 PM", location: "Johnson Residence", members: 18, memberIds: [], image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80" },
    ],
    followUps: [
      { id: "f1", name: "Paul & Anna Schmidt", note: "Visited Sunday, interested in young families group", assignee: "David O.", due: "May 30", priority: "High", column: "new" },
      { id: "f2", name: "Nadia Kouassi", note: "First-time visitor, moved from Lyon last month", assignee: "Sophie C.", due: "May 31", priority: "Medium", column: "new" },
      { id: "f3", name: "Rafael Torres", note: "Attended with friend, asked about baptism class", assignee: "James M.", due: "Jun 1", priority: "High", column: "new" },
      { id: "f4", name: "Mei Zhang", note: "Second call scheduled for Thursday", assignee: "Marie D.", due: "May 29", priority: "Medium", column: "inprogress" },
      { id: "f5", name: "Kevin O'Brien", note: "Connected to men's group, following up on membership", assignee: "Thomas B.", due: "Jun 3", priority: "Low", column: "inprogress" },
      { id: "f6", name: "Fatima Al-Hassan", note: "Email sent, awaiting response on small group interest", assignee: "Amara D.", due: "May 28", priority: "High", column: "inprogress" },
      { id: "f7", name: "Lucas & Émilie Petit", note: "Joined groups, fully integrated", assignee: "David O.", due: "May 25", priority: "Low", column: "completed" },
      { id: "f8", name: "George Mensah", note: "Completed new member class, baptized May 24", assignee: "James M.", due: "May 24", priority: "Medium", column: "completed" },
      { id: "f9", name: "Clara Fontaine", note: "Connected to worship team, very engaged", assignee: "Sophie C.", due: "May 22", priority: "Low", column: "completed" },
    ],
    appointmentHosts: [
      { id: "h1", name: "Pastor James Mitchell", role: "Lead Pastor", department: "Pastoral care", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80" },
      { id: "h2", name: "Sophie Chen", role: "Associate Pastor", department: "Pastoral care", initials: "SC" },
      { id: "h3", name: "David Okonkwo", role: "Membership Director", department: "People", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80" },
      { id: "h4", name: "Marie Dubois", role: "Prayer Coordinator", department: "Ministry", initials: "MD" },
    ],
    availableSlots: [
      { id: "s1", hostId: "h1", date: "2026-05-29", dateLabel: "Thu, May 29", time: "10:00", duration: "45 min", type: "Pastoral", location: "Office 2 · Main building", spotsLeft: 1 },
      { id: "s2", hostId: "h1", date: "2026-05-30", dateLabel: "Fri, May 30", time: "14:30", duration: "30 min", type: "Counseling", location: "Zoom · link sent on booking", spotsLeft: 2 },
      { id: "s3", hostId: "h2", date: "2026-05-29", dateLabel: "Thu, May 29", time: "11:15", duration: "30 min", type: "Prayer", location: "Prayer room · East wing", spotsLeft: 1 },
      { id: "s4", hostId: "h2", date: "2026-06-02", dateLabel: "Mon, Jun 2", time: "09:00", duration: "45 min", type: "Pastoral", location: "Office 1 · Main building", spotsLeft: 1 },
      { id: "s5", hostId: "h3", date: "2026-05-29", dateLabel: "Thu, May 29", time: "16:00", duration: "30 min", type: "Membership", location: "Welcome desk", spotsLeft: 3 },
      { id: "s6", hostId: "h3", date: "2026-06-03", dateLabel: "Tue, Jun 3", time: "13:00", duration: "30 min", type: "New visitor", location: "Café lounge", spotsLeft: 2 },
      { id: "s7", hostId: "h4", date: "2026-05-30", dateLabel: "Fri, May 30", time: "18:30", duration: "20 min", type: "Prayer", location: "Sanctuary · after service", spotsLeft: 4 },
    ],
    appointmentsToPlan: [
      { id: "p1", personName: "Paul & Anna Schmidt", personEmail: "p.schmidt@example.com", personPhone: "+33 6 12 34 56 78", preferredHost: "Pastor James Mitchell", requestedWindow: "Weekday mornings", status: "needs-slot", type: "New visitor", topic: "First follow-up after Sunday visit", notes: "Interested in young families group.", createdAt: "May 27" },
      { id: "p2", personName: "Nadia Kouassi", personEmail: "n.kouassi@example.com", preferredHost: "Sophie Chen", status: "pending-confirm", type: "Pastoral", topic: "Relocation & church integration", createdAt: "May 26" },
      { id: "p3", personName: "Rafael Torres", personEmail: "r.torres@example.com", personPhone: "+1 555 890 1234", requestedWindow: "Before Jun 10", status: "needs-slot", type: "Membership", topic: "Baptism class enrollment", createdAt: "May 25" },
      { id: "p4", personName: "Fatima Al-Hassan", personEmail: "f.alhassan@example.com", preferredHost: "Marie Dubois", status: "reschedule", type: "Prayer", topic: "Prayer request follow-up", notes: "Previous slot May 22 — unavailable.", createdAt: "May 24" },
      { id: "p5", personName: "Kevin O'Brien", personEmail: "k.obrien@example.com", status: "pending-confirm", type: "Counseling", topic: "Marriage enrichment session", createdAt: "May 23" },
    ],
    scheduledAppointments: [
      { id: "sa1", personName: "Mei Zhang", personEmail: "mei.z@example.com", hostId: "h2", hostName: "Sophie Chen", date: "2026-05-28", dateLabel: "Wed, May 28", time: "15:00", duration: "30 min", type: "Pastoral", location: "Office 1", status: "confirmed", topic: "Integration check-in" },
      { id: "sa2", personName: "Thomas Blanc", personEmail: "t.blanc@email.com", hostId: "h3", hostName: "David Okonkwo", date: "2026-05-29", dateLabel: "Thu, May 29", time: "11:00", duration: "30 min", type: "Membership", location: "Welcome desk", status: "confirmed", topic: "New member orientation" },
    ],
    contributions: [
      { id: "c1", memberId: "7", name: "James Moreau", fund: "General Tithe", amount: 250, method: "Online", date: "May 28, 2026", status: "Completed" },
      { id: "c2", memberId: "9", name: "Marie Dubois", fund: "Missions", amount: 100, method: "ACH", date: "May 27, 2026", status: "Completed" },
      { id: "c3", memberId: "1", name: "Sarah Jenkins", fund: "Building Campaign", amount: 500, method: "Check", date: "May 26, 2026", status: "Completed" },
      { id: "c4", name: "Anonymous", fund: "General Tithe", amount: 75, method: "Cash", date: "May 25, 2026", status: "Completed" },
      { id: "c5", memberId: "8", name: "Sophie Chen", fund: "General Tithe", amount: 150, method: "Online", date: "May 24, 2026", status: "Completed" },
      { id: "c6", memberId: "2", name: "Michael Roberts", fund: "Missions", amount: 50, method: "Online", date: "May 23, 2026", status: "Completed" },
      { id: "c7", memberId: "10", name: "Lucas Martin", fund: "General Tithe", amount: 200, method: "ACH", date: "May 22, 2026", status: "Completed" },
      { id: "c8", memberId: "4", name: "Emily Wong", fund: "Building Campaign", amount: 1000, method: "Check", date: "May 21, 2026", status: "Completed" },
    ],
    pledgeCampaigns: [
      { id: "pl1", name: "Building Campaign", goal: 120000, raised: 81600, pledgers: 142, deadline: "Dec 2026", color: "text-[#5932EA]", bg: "bg-[#e5deff]", bar: "bg-[#5932EA]", desc: "New sanctuary expansion and community center." },
      { id: "pl2", name: "Missions Fund 2026", goal: 45000, raised: 31200, pledgers: 89, deadline: "Dec 2026", color: "text-[#00677d]", bg: "bg-[#d4f0f7]", bar: "bg-[#00677d]", desc: "Supporting global and local mission partners." },
      { id: "pl3", name: "Youth Ministry", goal: 18000, raised: 14400, pledgers: 56, deadline: "Aug 2026", color: "text-violet-700", bg: "bg-violet-50", bar: "bg-violet-600", desc: "Summer camps and youth outreach programs." },
      { id: "pl4", name: "Benevolence Fund", goal: 10000, raised: 7800, pledgers: 34, deadline: "Ongoing", color: "text-amber-800", bg: "bg-amber-50", bar: "bg-amber-500", desc: "Emergency assistance for families in need." },
    ],
    givingStatements: [
      { id: "st1", memberId: "7", name: "James Moreau", email: "j.moreau@example.com", total: 3250, gifts: 12, period: "Q1 2026", status: "Sent" },
      { id: "st2", memberId: "1", name: "Sarah Jenkins", email: "sarah.j@example.com", total: 4800, gifts: 12, period: "Q1 2026", status: "Sent" },
      { id: "st3", memberId: "9", name: "Marie Dubois", email: "marie.d@email.com", total: 2100, gifts: 12, period: "Q1 2026", status: "Ready" },
      { id: "st4", memberId: "2", name: "Michael Roberts", email: "m.roberts@example.com", total: 1800, gifts: 12, period: "Q1 2026", status: "Ready" },
      { id: "st5", memberId: "8", name: "Sophie Chen", email: "s.chen@example.com", total: 2400, gifts: 12, period: "Q1 2026", status: "Ready" },
      { id: "st6", memberId: "4", name: "Emily Wong", email: "emily.w@example.com", total: 3600, gifts: 12, period: "Q1 2026", status: "Sent" },
      { id: "st7", memberId: "10", name: "Lucas Martin", email: "l.martin@email.com", total: 1500, gifts: 12, period: "Q1 2026", status: "Ready" },
      { id: "st8", memberId: "3", name: "David Chen", email: "d.chen@example.com", total: 900, gifts: 8, period: "Q1 2026", status: "Ready" },
    ],
    financeAccounts: [
      { id: "fa1", name: "General Fund", balance: 42300, color: "bg-[#5932EA]" },
      { id: "fa2", name: "Building Fund", balance: 81600, color: "bg-[#00677d]" },
      { id: "fa3", name: "Missions Fund", balance: 14200, color: "bg-violet-500" },
      { id: "fa4", name: "Payroll", balance: 18500, color: "bg-amber-500" },
    ],
    financeTransactions: [
      { id: "t1", desc: "Sunday offering deposit", category: "Giving", amount: 12450, type: "income", date: "May 26, 2026", accountId: "fa1" },
      { id: "t2", desc: "Staff payroll — May", category: "Payroll", amount: 18500, type: "expense", date: "May 25, 2026", accountId: "fa4" },
      { id: "t3", desc: "Building pledge transfer", category: "Transfer", amount: 5200, type: "income", date: "May 24, 2026", accountId: "fa2" },
      { id: "t4", desc: "Utilities — May", category: "Facilities", amount: 1840, type: "expense", date: "May 23, 2026", accountId: "fa1" },
      { id: "t5", desc: "Mission partner support", category: "Missions", amount: 2500, type: "expense", date: "May 22, 2026", accountId: "fa3" },
      { id: "t6", desc: "Online giving batch", category: "Giving", amount: 8920, type: "income", date: "May 21, 2026", accountId: "fa1" },
      { id: "t7", desc: "Youth event supplies", category: "Ministry", amount: 420, type: "expense", date: "May 20, 2026", accountId: "fa1" },
      { id: "t8", desc: "Benevolence disbursement", category: "Benevolence", amount: 800, type: "expense", date: "May 19, 2026", accountId: "fa1" },
    ],
    budgetCategories: [
      { id: "b1", name: "Staff Salaries", budget: 220000, spent: 92500, color: "bg-[#5932EA]", status: "on-track" },
      { id: "b2", name: "Facilities & Utilities", budget: 48000, spent: 19200, color: "bg-[#00677d]", status: "on-track" },
      { id: "b3", name: "Ministry Programs", budget: 36000, spent: 15800, color: "bg-violet-500", status: "on-track" },
      { id: "b4", name: "Missions", budget: 24000, spent: 11200, color: "bg-teal-500", status: "on-track" },
      { id: "b5", name: "Events & Hospitality", budget: 18000, spent: 16400, color: "bg-amber-500", status: "over-budget" },
      { id: "b6", name: "Technology", budget: 12000, spent: 4200, color: "bg-blue-500", status: "under-budget" },
      { id: "b7", name: "Benevolence Fund", budget: 15000, spent: 14200, color: "bg-rose-500", status: "over-budget" },
      { id: "b8", name: "Worship & Music", budget: 8000, spent: 3100, color: "bg-indigo-500", status: "on-track" },
      { id: "b9", name: "Children & Youth", budget: 14000, spent: 5800, color: "bg-pink-500", status: "on-track" },
      { id: "b10", name: "Communications", budget: 6000, spent: 2400, color: "bg-cyan-500", status: "on-track" },
    ],
    forms: [
      { id: "form1", name: "New Member Registration", category: "Membership", status: "Active", fields: [{ id: "f1", type: "text", label: "Full Name", required: true }, { id: "f2", type: "email", label: "Email", required: true }, { id: "f3", type: "phone", label: "Phone" }, { id: "f4", type: "textarea", label: "How did you hear about us?" }], submissions: 28, lastSubmit: "2 hours ago" },
      { id: "form2", name: "Prayer Request", category: "Pastoral", status: "Active", fields: [{ id: "f1", type: "text", label: "Name", required: true }, { id: "f2", type: "textarea", label: "Prayer Request", required: true }, { id: "f3", type: "checkbox", label: "Keep confidential" }], submissions: 124, lastSubmit: "30 min ago" },
      { id: "form3", name: "Volunteer Sign-up", category: "Events", status: "Active", fields: [{ id: "f1", type: "text", label: "Name", required: true }, { id: "f2", type: "select", label: "Ministry Area", options: ["Hospitality", "Kids", "Worship", "Tech"] }], submissions: 64, lastSubmit: "1 day ago" },
      { id: "form4", name: "Pastoral Care Request", category: "Pastoral", status: "Draft", fields: [{ id: "f1", type: "text", label: "Name" }, { id: "f2", type: "textarea", label: "How can we help?" }], submissions: 0, lastSubmit: "—" },
    ],
    formSubmissions: [
      { id: "S-0348", formId: "form2", form: "Prayer Request", name: "Marie Dubois", email: "marie.d@email.com", submitted: "May 28, 9:42 AM", status: "Reviewed", answers: { Name: "Marie Dubois", "Prayer Request": "Healing for my mother", "Keep confidential": "Yes" } },
      { id: "S-0347", formId: "form3", form: "Volunteer Sign-up", name: "Lucas Martin", email: "l.martin@email.com", submitted: "May 28, 8:15 AM", status: "Pending", answers: { Name: "Lucas Martin", "Ministry Area": "Worship" } },
      { id: "S-0346", formId: "form1", form: "New Member Registration", name: "Nadia Kouassi", email: "n.kouassi@example.com", submitted: "May 27, 6:30 PM", status: "Pending", answers: { "Full Name": "Nadia Kouassi", Email: "n.kouassi@example.com", Phone: "+1 555 567-8901" } },
      { id: "S-0345", formId: "form2", form: "Prayer Request", name: "Thomas Blanc", email: "t.blanc@email.com", submitted: "May 27, 5:00 PM", status: "Reviewed", answers: { Name: "Thomas Blanc", "Prayer Request": "Job search guidance" } },
    ],
    calendarEvents: [
      { id: "e1", title: "Sunday Worship Service", date: "2026-06-01", time: "9:30 AM", endTime: "11:00 AM", attendees: 320, category: "Ministry", color: "border-blue-200/80 bg-blue-50/30", dot: "bg-blue-500", location: "Main Sanctuary", status: "confirmed" },
      { id: "e2", title: "Youth Night", date: "2026-05-30", time: "7:00 PM", attendees: 48, category: "Fellowship", color: "border-violet-200/80 bg-violet-50/30", dot: "bg-violet-500", location: "Youth Hall", status: "confirmed" },
      { id: "e3", title: "Prayer Meeting", date: "2026-06-04", time: "6:00 PM", attendees: 22, category: "Ministry", color: "border-amber-200/80 bg-amber-50/30", dot: "bg-amber-500", status: "draft" },
      { id: "e4", title: "Worship Practice", date: "2026-05-31", time: "10:00 AM", attendees: 14, category: "Ministry", color: "border-emerald-200/80 bg-emerald-50/30", dot: "bg-emerald-500", status: "confirmed" },
      { id: "e5", title: "Community Food Drive", date: "2026-06-07", time: "8:00 AM", category: "Outreach", color: "border-teal-200/80 bg-teal-50/30", dot: "bg-teal-500", location: "Parking Lot" },
    ],
    volunteerRoles: [
      { id: "vr1", role: "Greeters & Ushers", icon: "Users", slots: [
        { id: "vs1", roleId: "vr1", name: "Amara Diallo", event: "Sunday Service", date: "Jun 1", status: "Confirmed" },
        { id: "vs2", roleId: "vr1", name: "Lucas Martin", event: "Sunday Service", date: "Jun 1", status: "Pending" },
      ]},
      { id: "vr2", role: "Kids Ministry", icon: "Baby", slots: [
        { id: "vs3", roleId: "vr2", name: "Sophie Chen", event: "Sunday Service", date: "Jun 1", status: "Confirmed" },
        { id: "vs4", roleId: "vr2", name: "Emily Wong", event: "Youth Night", date: "May 30", status: "Unconfirmed" },
      ]},
      { id: "vr3", role: "AV & Media", icon: "Monitor", slots: [
        { id: "vs5", roleId: "vr3", name: "Hugo Renard", event: "Sunday Service", date: "Jun 1", status: "Confirmed" },
      ]},
    ],
    checkIns: [
      { id: "ci1", name: "Marie Dubois", time: "9:28 AM", event: "Sunday Service", type: "QR Code", avatar: "MD", color: "from-violet-500 to-[#5932EA]" },
      { id: "ci2", name: "James Moreau", time: "9:31 AM", event: "Sunday Service", type: "QR Code", avatar: "JM", color: "from-indigo-500 to-violet-600" },
      { id: "ci3", name: "Lucas Martin", time: "9:35 AM", event: "Sunday Service", type: "Manual", avatar: "LM", color: "from-cyan-500 to-blue-500" },
      { id: "ci4", name: "Nadia Kouassi", time: "9:42 AM", event: "Sunday Service", type: "QR Code", avatar: "NK", color: "from-emerald-500 to-teal-600" },
      { id: "ci5", name: "Paul Schmidt", time: "9:45 AM", event: "Sunday Service", type: "Manual", avatar: "PS", color: "from-amber-500 to-orange-500" },
      { id: "ci6", name: "Sophie Chen", time: "9:50 AM", event: "Sunday Service", type: "QR Code", avatar: "SC", color: "from-teal-500 to-cyan-600" },
    ],
    emails: [
      { id: "em1", subject: "This Week at Lumina Church", audience: "All Members", body: "Join us this Sunday...", sent: "May 26, 2026", opens: 824, clicks: 312, status: "Sent" },
      { id: "em2", subject: "Easter Sunday Details & Schedule", audience: "All Members", sent: "May 20, 2026", opens: 968, clicks: 524, status: "Sent" },
      { id: "em3", subject: "Palm Sunday Special Service", audience: "All Members", body: "Draft content...", lastEdited: "2 hours ago", status: "Draft" },
      { id: "em4", subject: "Good Friday Vigil — May 17", audience: "All Members", lastEdited: "Yesterday", status: "Draft" },
    ],
    smsMessages: [
      { id: "sms1", text: "Reminder: Youth Night tonight at 7 PM. See you there!", audience: "Youth & Parents", sent: "May 29, 4:00 PM", recipients: 86, status: "Delivered" },
      { id: "sms2", text: "Thank you for giving today. Your generosity makes a difference!", audience: "Today's Givers", sent: "May 26, 12:30 PM", recipients: 42, status: "Delivered" },
      { id: "sms3", text: "Prayer meeting moved to Room 204 this Wednesday.", audience: "Prayer Team", sent: "May 24, 10:00 AM", recipients: 18, status: "Delivered" },
      { id: "sms4", text: "Volunteer spots still open for Sunday. Reply YES to confirm.", audience: "Volunteers", sent: "May 23, 6:00 PM", recipients: 124, status: "Delivered" },
    ],
    notifications: [
      { id: "n1", title: "New member registration", body: "Nadia Kouassi submitted a new member form.", sent: "2 hours ago", type: "Action", icon: "UserPlus", color: "text-[#5932EA]", read: false, href: "/members/6" },
      { id: "n2", title: "Contribution received", body: "James Moreau gave $250 to General Tithe.", sent: "5 hours ago", type: "Finance", icon: "Heart", color: "text-emerald-600", read: false, href: "/giving/contributions" },
      { id: "n3", title: "Youth Night tomorrow", body: "48 registered attendees for Friday event.", sent: "Yesterday", type: "Event", icon: "Calendar", color: "text-violet-600", read: true, href: "/events/calendar" },
      { id: "n4", title: "Form submission pending", body: "Lucas Martin signed up to volunteer.", sent: "Yesterday", type: "Content", icon: "FileText", color: "text-amber-600", read: true, href: "/forms/submissions" },
    ],
    worshipSongs: [
      { id: "ws1", title: "Great Are You Lord", artist: "All Sons & Daughters", key: "G", tempo: "72 BPM", tags: ["Worship", "Opening"], lastPlayed: "May 26" },
      { id: "ws2", title: "Way Maker", artist: "Sinach", key: "D", tempo: "128 BPM", tags: ["Praise"], lastPlayed: "May 26" },
      { id: "ws3", title: "Build My Life", artist: "Housefires", key: "A", tempo: "68 BPM", tags: ["Worship"], lastPlayed: "May 19" },
      { id: "ws4", title: "Goodness of God", artist: "Bethel Music", key: "C", tempo: "74 BPM", tags: ["Worship", "Closing"], lastPlayed: "May 26" },
      { id: "ws5", title: "Reckless Love", artist: "Cory Asbury", key: "E", tempo: "84 BPM", tags: ["Worship"], lastPlayed: "May 12" },
    ],
    servicePlans: [
      { id: "sp1", date: "Jun 1, 2026", time: "9:30 AM", title: "Sunday Morning Service", theme: "Walking in Faith", leader: "Amara Diallo", status: "confirmed", items: [
        { id: "i1", time: "9:30", duration: "5 min", type: "worship", label: "Pre-Service Worship", icon: "Music", color: "text-violet-600" },
        { id: "i2", time: "9:35", duration: "10 min", type: "worship", label: "Opening Songs", icon: "Music", color: "text-violet-600" },
        { id: "i3", time: "9:45", duration: "5 min", type: "announcement", label: "Welcome & Announcements", icon: "Megaphone", color: "text-blue-600" },
        { id: "i4", time: "9:50", duration: "35 min", type: "sermon", label: "Sermon: Walking in Faith", icon: "BookOpen", color: "text-amber-600" },
        { id: "i5", time: "10:25", duration: "5 min", type: "offering", label: "Offering", icon: "Heart", color: "text-emerald-600" },
      ]},
      { id: "sp2", date: "May 25, 2026", time: "9:30 AM", title: "Sunday Morning Service", theme: "Grace Abounds", leader: "Sophie Chen", status: "confirmed", items: [] },
      { id: "sp3", date: "Jun 8, 2026", time: "9:30 AM", title: "Sunday Morning Service", theme: "TBD", leader: "Amara Diallo", status: "draft", items: [] },
    ],
    staff: [
      { id: "stf1", name: "Pastor Admin", email: "pastor@luminachurch.org", role: "Lead Pastor", status: "Active" },
      { id: "stf2", name: "Sophie Chen", email: "s.chen@example.com", role: "Associate Pastor", status: "Active" },
      { id: "stf3", name: "David Okonkwo", email: "d.okonkwo@luminachurch.org", role: "Membership Director", status: "Active" },
      { id: "stf4", name: "Marie Dubois", email: "marie.d@email.com", role: "Admin Assistant", status: "Invited" },
    ],
    settings: {
      churchName: "Lumina Community Church",
      denomination: "Non-denominational",
      phone: "+1 555 001 0000",
      email: "hello@luminachurch.org",
      address: "123 Faith Avenue, Montreal, QC, Canada H1A 2B3",
      mission: "Connecting people to God, to each other, and to their purpose through authentic community and transformational faith.",
      timezone: "America/Montreal",
      dateFormat: "DD/MM/YYYY",
      currency: "CAD",
      notificationPrefs: {
        newMember: true,
        formSubmission: true,
        givingReceived: true,
        volunteerConfirmation: true,
        weeklySummary: true,
      },
    },
  };
}
